### ISSUE TITLE
Readme Unicorn config sample is incorrect

### ISSUE THREAD

**Issue by michaellwest** [delawarePro/sitecore-data-blaster#17]
I was able to get the following working on Unicorn 4.0.4 and Sitecore 8.2.7.

The following is to demonstrate the processor syntax.
```xml
<pipelines>
  <unicornSyncStart>
    <processor type="Unicorn.DataBlaster.Sync.UnicornDataBlaster, Unicorn.DataBlaster">
      <param hint="1" type="Sitecore.DataBlaster.Load.BulkLoader, Sitecore.DataBlaster" />
      <param hint="2" type="Unicorn.DataBlaster.Sync.ItemExtractor, Unicorn.DataBlaster">
        <param hint="1" type="Unicorn.DataBlaster.Sync.ItemMapper, Unicorn.DataBlaster" />
      </param>
    </processor>
  </unicornSyncStart>
</pipelines>
```

**Comment by Elyseum** [comment]
Can you explain what's 'incorrect' about the config sample? Explicitly specifying the parameters is not needed as we create them in code if null.

**Comment by michaellwest** [comment]
If I recall correctly I needed to update the <processor> node to include the parameters because it could not instantiate the types.

**Comment by michaellwest** [comment]
Without the change this is the error I see:

![image](https://user-images.githubusercontent.com/933163/75189774-87f27e00-5714-11ea-9f82-e3fad1c6808b.png)

**Comment by Elyseum** [comment]
Apparently Sitecore's CreateFromTypeName doesn't support optional parameters (yet). I added additional constructors to fix this. 
We didn't spot the issue ourselves because we use a custom DataBlaster with default ctor that inherits from this one.

**Comment by michaellwest** [comment]
Thank you very much @Elyseum . I appreciate you having a look at this issue.
